[project]
name = "agent"
version = "0.1.0"
description = ""
authors = [
    {name = "orca-copilotkit",email = "testapp@copilotkit.ai"}
]
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "google (==3.0.0)",
    "google-genai (==1.28.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "google-generativeai (>=0.8.5,<0.9.0)",
    "fastapi (>=0.115.0,<0.116.0)",
    "uvicorn (>=0.35.0,<0.36.0)",
    "langgraph (==0.6.3)",
    "langchain-core (==0.3.72)",
    "copilotkit (==0.1.58)",
    "langchain[google-genai] (==0.3.26)",
    "requests (>=2.31.0,<3.0.0)"
]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
